### ISSUE TITLE
[Bug] new release of pypa/packaging might break openbb 

### ISSUE THREAD

**Issue by koioannis** [OpenBB-finance/OpenBB#3750]
**Describe the bug**
I think new [release](https://github.com/pypa/packaging/releases/tag/22.0) of `pypa/packaging` breaks openbb

**To Reproduce**
```
conda create -n obb python=3.9.6 -y
conda activate obb
pip install openbb
touch main.py
```
In `main.py`:
```
from openbb_terminal.sdk import openbb
```
then:
```
python main.py
```
results to:

```
Traceback (most recent call last):
  File "/Users/koioannis/dev/work/gdx/new-openbb/main.py", line 1, in <module>
    from openbb_terminal.sdk import openbb
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/sdk.py", line 19, in <module>
    openbb = Breadcrumb(
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/core/library/breadcrumb.py", line 105, in __init__
    BreadcrumbLogger()
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/core/library/breadcrumb.py", line 151, in __init__
    self.__check_initialize_logging()
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/core/library/breadcrumb.py", line 155, in __check_initialize_logging
    self.__initialize_logging()
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/core/library/breadcrumb.py", line 160, in __initialize_logging
    from openbb_terminal.core.log.generation.settings_logger import (  # pylint: disable=C0415
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/core/log/generation/settings_logger.py", line 13, in <module>
    from openbb_terminal.terminal_helper import is_packaged_application
  File "/Users/koioannis/opt/miniconda3/envs/obb/lib/python3.9/site-packages/openbb_terminal/terminal_helper.py", line 283, in <module>
    latest_version: Union[version.LegacyVersion, version.Version],
AttributeError: module 'packaging.version' has no attribute 'LegacyVersion'
```

**Desktop:**

- OS: MacOS Monterey 12.6
- Python version 3.9.6

**Comment by albergar2** [comment]
Experiencing the same issue as @koioannis

**Comment by jmaslek** [comment]
This _should_ be fixed by running `pip install packaging==21` in your environment

We will look into getting this resolved with a potential solution being mentioned by @hjoaquim in one of the open PRs

**Comment by jmaslek** [comment]
We have resolved the issue and updated the dependency.  we put out a 2.0.1 on pip (`pip install -U openbb` should address anyone else that runs into this)
