### ISSUE TITLE
Problem during installation 

### ISSUE THREAD

**Issue by Jacques2101** [OpenBB-finance/OpenBB#6610]
**Describe the bug**
During the installation process I receive this error message 
Downloading plotly-5.23.0-py3-none-any.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━ 11.8/17.3 MB 184.1 kB/s eta 0:00:31
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/http/client.py", line 473, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/ssl.py", line 1314, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/ssl.py", line 1166, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 554, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 469, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/network/download.py", line 184, in __call__
    for chunk in chunks:
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_internal/network/utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/jacques/miniconda3/envs/openbb/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**To Reproduce**
pip install "openbb[all]"

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra] Mac 
- Python version [e.g. 3.6.8] : 3.11.9

**Comment by deeleeramone** [comment]
Hi there, 

This is a network error, specifically during the download of Plotly. Check your network connection and configuration and try again.
